### ISSUE TITLE
"œ" is not "oe" => search results issue

### ISSUE THREAD

**Issue by postb99** [poesieland/poesieland.github.io#47]
Whoever would lookup for "cœur" using a standard french keyboard? Rather just type "coeur" but then "cœur" occurrences won't be found.

Update .md and storage files to use "œ" everywhere.

Find out what to add for Lucene rule, something like https://stackoverflow.com/questions/40991721/how-to-search-in-lucene-using-symbol-synonims

Found: https://lunrjs.com/guides/customising.html#pipeline-functions

**Comment by postb99** [comment]
@McShelby hello, I'm interested in including a custom javascript, how can I include it on "all pages"? Or at least include it on pages that include lunr.js. I don't know where to place my shortcode, if this approach works.

Could it be done using https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html#own-shortcodes-with-javascript-dependencies procedure? I started something based on it, see test branch above (feel free to commit onto this branch if you wish).

Can you elaborate about the theme's shipped javascript (mermaid etc), is there one included "everywhere"? Because there is a disabling option but I didn't find where it is used :)

By the way, which Lunr version does the theme use? Neither theme credits page nor lunr javascript files seem to provide the info.

**Comment by McShelby** [comment]
Hi Barbara,

if you've set 

````
[outputs]
  home = ["searchpage"]
````

`lunr.js` will be included in every generated HTML file.

Please note, that this condition will change once I've finished [#888](https://github.com/McShelby/hugo-theme-relearn/issues/888). This issue is brand new but will most likely be included in the upcoming version 6.2.0.

The Javascript-Dependency mechanism is explicitly for shortcodes.

So the easiest way for you is to add a file `layouts/partials/custom-header.html` and put your necessary HTML into this. The custom header will be included in the `<head>`of every generated HTML file.

**Comment by postb99** [comment]
![image](https://github.com/user-attachments/assets/2bb2bf43-c468-47cb-b35b-63e4df81738e)

Hello @McShelby I'm sorry my included file (in footer, not header) doesn't find "lunr", what could solve it? Thanks for your time :)

**Comment by McShelby** [comment]
Hi Barbara. As you can see from your browsers network tab, the `plugin.js` file is successfully loaded (I just tested the home page of your project).

But anyways, you're getting an error in line 20 in the console and that's because your IIFE misses the parameter `builder`. You expect that in the function signature in line 1 but fail to provide it, when you call it in line 22.

`lunr` itself was available in my test but because of the `defer` attribute, it might has timing issues.

![grafik](https://github.com/user-attachments/assets/e3d4eba5-bb55-4a3e-93f3-2d5aedb4d6c2)

**Comment by postb99** [comment]
https://github.com/poesieland/poesieland.github.io/issues/48

**Comment by postb99** [comment]
For now I've setup custom code that solves my issue. It will undergo improvements. 

https://github.com/postb99/hugo-theme-relearn-lunr-customization
